import React, { useState } from 'react';
import { PHONE_NUMBER, PHONE_DISPLAY, WHATSAPP_NUMBER, BRANCHES_DATA } from '../data/siteData';
import { Phone, MapPin, Send, Mail, Clock3, MessageCircle } from 'lucide-react';

export const ContactSection: React.FC = () => {
  const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [service, setService] = useState(''); const [details, setDetails] = useState('');
  const submit = (e: React.FormEvent) => { e.preventDefault(); if (!name.trim() || !phone.trim()) return; const msg = `طلب خدمة من الموقع\n------------------\nالاسم: ${name.trim()}\nالجوال: ${phone.trim()}\nنوع الخدمة: ${service || 'خدمة أخرى / استفسار عام'}${details.trim() ? `\nالتفاصيل: ${details.trim()}` : ''}`; window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(msg)}`, '_blank'); };
  return <section id="contact" className="py-20 bg-[#a7a9ac] relative overflow-hidden">
    <div className="container mx-auto px-4 lg:max-w-6xl relative z-10"><div className="text-center mb-12"><h2 className="text-4xl md:text-5xl font-black text-rkNavyDeep mb-4">تواصل معنا الآن</h2><p className="text-gray-700 text-lg">إذا كنت تريد طلب معاينة أو لديك أي استفسار حول خدماتنا، يسعدنا تواصلك معنا لتقديم الدعم الكامل.</p></div>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-stretch">
        <div className="bg-[#cdc9c1] rounded-3xl p-8 md:p-10 shadow-xl relative overflow-hidden rk-reveal"><div className="absolute -top-20 -right-20 w-64 h-64 bg-[#dfdcd6] rounded-full opacity-50 pointer-events-none"/><h3 className="text-2xl font-bold text-[#0F2E3D] mb-8 relative z-10 text-center lg:text-right">طلب خدمة أو استفسار</h3><div className="w-full h-0.5 bg-rkGold mb-8"/><form onSubmit={submit} className="relative z-10"><div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6"><label className="block text-[#0F2E3D] font-bold text-sm text-right">الاسم الكريم <span className="text-red-600">*</span><input value={name} onChange={e=>setName(e.target.value)} required className="mt-2 w-full bg-transparent border border-gray-400 rounded-lg px-4 py-3 focus:outline-none focus:border-[#0F2E3D] focus:bg-white/50 transition-colors placeholder-gray-500 font-normal" placeholder="أدخل اسمك بالكامل"/></label><label className="block text-[#0F2E3D] font-bold text-sm text-right">رقم الجوال <span className="text-red-600">*</span><input value={phone} onChange={e=>setPhone(e.target.value)} required dir="ltr" className="mt-2 w-full bg-transparent border border-gray-400 rounded-lg px-4 py-3 text-right focus:outline-none focus:border-[#0F2E3D] focus:bg-white/50 transition-colors placeholder-gray-500 font-normal" placeholder="05x xxx xxxx"/></label></div><label className="block text-[#0F2E3D] font-bold text-sm text-right mb-6">نوع الخدمة المطلوبة<select value={service} onChange={e=>setService(e.target.value)} className="mt-2 w-full bg-transparent border border-gray-400 rounded-lg px-4 py-3 appearance-none focus:outline-none focus:border-[#0F2E3D] focus:bg-white/50 transition-colors cursor-pointer text-gray-700 font-normal"><option value="" disabled>اختر الخدمة من القائمة...</option><option>تحديث الصك</option><option>فرز الصكوك العقارية</option><option>دمج الصكوك</option><option>استخراج صك بديل (تالف/مفقود)</option><option>نقل ملكية الصك</option><option>خدمة أخرى / استفسار عام</option></select></label><label className="block text-[#0F2E3D] font-bold text-sm text-right mb-8">تفاصيل الطلب (اختياري)<textarea value={details} onChange={e=>setDetails(e.target.value)} rows={4} className="mt-2 w-full bg-transparent border border-gray-400 rounded-lg px-4 py-3 focus:outline-none focus:border-[#0F2E3D] focus:bg-white/50 transition-colors placeholder-gray-500 resize-none font-normal" placeholder="اكتب تفاصيل مشروعك أو استفسارك هنا..."/></label><button type="submit" className="w-full bg-[#112a35] hover:bg-[#0a1b22] text-white font-bold text-lg py-4 rounded-xl transition-colors flex items-center justify-center gap-3"><span>إرسال الطلب</span><Send className="w-5 h-5"/></button></form></div>
        <div className="bg-[#112a35] rounded-3xl p-8 md:p-12 shadow-xl relative overflow-hidden rk-reveal delay-100 flex flex-col justify-center text-right"><div className="absolute -bottom-20 -left-20 w-80 h-80 rounded-full border-[30px] border-[#163645] opacity-50 pointer-events-none"/><div className="absolute -bottom-10 -left-10 w-60 h-60 rounded-full border-[20px] border-[#1a4254] opacity-30 pointer-events-none"/><h3 className="text-3xl font-black text-[#dcb13c] mb-12 relative z-10 text-center lg:text-right">معلومات الاتصال</h3><div className="space-y-9 relative z-10"><div className="flex items-center gap-6 justify-end"><div><div className="text-gray-400 text-sm mb-1">الرقم المباشر</div><a href={`tel:${PHONE_NUMBER}`} className="text-white font-bold text-xl hover:text-[#dcb13c] transition-colors block" dir="ltr">{PHONE_DISPLAY}</a></div><div className="w-14 h-14 bg-[#1a3a47] rounded-2xl flex items-center justify-center text-[#dcb13c] text-xl"><Phone/></div></div><div className="flex items-center gap-6 justify-end"><div><div className="text-gray-400 text-sm mb-1">البريد الإلكتروني</div><a href="mailto:info@ryan-sa.com" className="text-white font-bold text-lg hover:text-[#dcb13c] transition-colors">info@ryan-sa.com</a></div><div className="w-14 h-14 bg-[#1a3a47] rounded-2xl flex items-center justify-center text-[#dcb13c] text-xl"><Mail/></div></div><div className="flex items-center gap-6 justify-end"><div><div className="text-gray-400 text-sm mb-1">واتساب</div><a href={`https://wa.me/${WHATSAPP_NUMBER}`} target="_blank" rel="noreferrer" className="text-white font-bold text-xl hover:text-[#dcb13c] transition-colors block" dir="ltr">{PHONE_DISPLAY}</a></div><div className="w-14 h-14 bg-[#25D366] rounded-2xl flex items-center justify-center text-white text-xl"><MessageCircle/></div></div><div className="flex items-start gap-6 justify-end"><div className="text-right"><div className="text-gray-400 text-sm mb-2">فروعنا</div><ul className="text-white text-sm leading-8">{BRANCHES_DATA.map(branch=><li key={branch.city}><strong>{branch.city}:</strong> {branch.address}</li>)}</ul></div><div className="w-14 h-14 bg-[#1a3a47] rounded-2xl flex items-center justify-center text-[#dcb13c] text-xl"><MapPin/></div></div><div className="pt-5 border-t border-white/10 flex items-center justify-between text-xs text-gray-400"><span>السبت - الخميس</span><span className="text-[#dcb13c] font-semibold">8:00 ص - 9:00 م</span><Clock3 className="w-4 h-4"/></div></div></div>
      </div>
    </div>
  </section>;
};
