import React, { lazy, Suspense, useState } from 'react';
import { PHONE_NUMBER, WHATSAPP_NUMBER } from '../data/siteData';
import { Phone, CheckCircle2, ShieldCheck, Award, Zap } from 'lucide-react';
import { MultiStepConsultation } from './MultiStepConsultation';
const ThreeHeroWorld = lazy(() => import('../../components/hero/ThreeHeroWorld').then(module => ({ default: module.ThreeHeroWorld })));

export interface HeroConfig { eyebrow?: string; headline?: string; highlightedHeadline?: string; description?: string; defaultService?: string; choices?: string[]; formTitle?: string; ctaLabel?: string; whatsappMessage?: string; }
export const Hero: React.FC<{ config?: HeroConfig }> = ({ config }) => {
  const [wireframe, setWireframe] = useState(false);
  return <section id="home" className="min-h-[92vh] flex flex-col justify-center pt-28 pb-16 relative overflow-hidden bg-[#fef3c7]">
    <div className="absolute inset-0 z-0"><Suspense fallback={<div className="absolute inset-0 bg-[#fef3c7]" />}><ThreeHeroWorld wireframe={wireframe} autoTour parallaxEnabled shadowsEnabled cameraPreset="skyline"/></Suspense></div>
    <div className="absolute inset-0 z-[1] bg-gradient-to-l from-[#2B0F16]/50 via-[#2B0F16]/25 to-[#2B0F16]/35 pointer-events-none"/>
    <div className="container mx-auto px-4 lg:max-w-7xl relative z-10"><div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
      <div className="lg:col-span-7 text-center lg:text-right"><div className="flex flex-wrap items-center justify-center lg:justify-start gap-2 mb-6"><div className="inline-flex items-center gap-2 bg-neutral-900/80 text-[#FEB922] px-3.5 py-1.5 rounded-full text-xs font-bold border border-amber-400/30 backdrop-blur-md shadow-lg"><CheckCircle2 className="w-3.5 h-3.5"/><span>{config?.eyebrow || 'مكتب استشارات هندسية ومساحية مرخص'}</span></div><div className="inline-flex items-center gap-1.5 bg-neutral-900/80 text-stone-200 px-3 py-1.5 rounded-full text-xs font-medium border border-white/15 backdrop-blur-md shadow-lg"><ShieldCheck className="w-3.5 h-3.5 text-emerald-400"/><span>اعتماد بلدي • إحكام • كتابة العدل</span></div><button type="button" onClick={()=>setWireframe(v=>!v)} className="inline-flex items-center gap-1.5 bg-neutral-900/80 hover:bg-neutral-950 text-stone-300 hover:text-[#FEB922] px-3.5 py-1.5 rounded-full text-[11px] font-semibold border border-amber-400/30 backdrop-blur-md transition-all cursor-pointer shadow-lg"><span className="w-2 h-2 rounded-full bg-[#FEB922] animate-pulse"/><span>{wireframe ? 'إظهار التجسيم الواقعي' : 'عرض الشبكة الهندسية'}</span></button></div>
        <div className="bg-gradient-to-l from-[#3F1620]/35 via-[#2B0F16]/25 to-[#3F1620]/15 backdrop-blur-[2.5px] rounded-2xl sm:rounded-3xl p-4 sm:p-6 border border-[#C9973C]/25 shadow-xl mb-3.5"><h1 className="text-2xl sm:text-3xl md:text-4xl lg:text-[2.6rem] xl:text-[2.9rem] font-black text-white leading-[1.3] tracking-tight drop-shadow-[0_2px_4px_rgba(0,0,0,.95)]">{config?.headline || 'أفضل مكتب معتمد في المملكة'} <br className="hidden sm:inline"/><span className="text-transparent bg-clip-text bg-gradient-to-l from-[#F2C230] via-[#FEB922] to-[#F7D97A]">{config?.highlightedHeadline || 'لتحديث الصكوك'}</span></h1></div>
        <div className="bg-gradient-to-l from-[#3F1620]/30 via-[#2B0F16]/20 to-[#3F1620]/10 backdrop-blur-[2px] rounded-2xl p-3.5 sm:p-4 border border-[#C9973C]/20 shadow-lg mb-8 max-w-2xl mx-auto lg:mx-0"><p className="text-sm sm:text-base md:text-lg text-white leading-relaxed font-medium drop-shadow-[0_2px_4px_rgba(0,0,0,.95)]">{config?.description || 'مكتب ريان للمساحة والاستشارات الهندسية — نجمع بين دقة الرصد الميداني والخبرة النظامية الشاملة في تحديث، فرز، دمج، وتوثيق الصكوك العقارية إلكترونياً بأعلى معايير الاعتماد والسرعة.'}</p></div>
        <div className="flex flex-col sm:flex-row gap-4 justify-center lg:justify-start items-center"><a href={`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(config?.whatsappMessage || 'السلام عليكم، أرغب في استشارة هندسية سريعة لتحديث صك عقاري')}`} target="_blank" rel="noopener noreferrer" className="w-full sm:w-auto rk-btn bg-[#25D366] hover:bg-[#20bd5a] text-white font-bold py-3.5 px-8 rounded-xl flex items-center justify-center gap-2.5 text-base sm:text-lg shadow-xl"><span>استشارة فورية عبر الواتساب</span></a><a href={`tel:${PHONE_NUMBER}`} className="w-full sm:w-auto rk-btn rk-btn-call bg-[#C9973C] hover:bg-[#B8860B] text-[#2B0F16] font-extrabold py-3.5 px-8 rounded-xl flex items-center justify-center gap-2.5 text-base sm:text-lg shadow-xl border border-amber-200"><Phone className="w-5 h-5 fill-current"/><span>اتصل بنا الآن</span></a></div>
        <div className="mt-10 grid grid-cols-1 sm:grid-cols-3 gap-3.5 pt-8 border-t border-neutral-800/60"><Trust icon={<ShieldCheck/>} title="اعتماد رسمي" text="منصات بلدي وإحكام"/><Trust icon={<Award/>} title="خبرة 15+ سنة" text="كوادر هندسية ومساحية"/><Trust icon={<Zap/>} title="إنجاز قياسي" text="توثيق إلكتروني سريع"/></div>
      </div><div className="lg:col-span-5 relative z-10"><MultiStepConsultation/></div>
    </div></div>
  </section>;
};
const Trust=({icon,title,text}:{icon:React.ReactElement<{className?: string}>;title:string;text:string})=><div className="flex items-center gap-3 bg-neutral-900/80 p-3 rounded-2xl border border-white/10 text-right backdrop-blur-md shadow-lg"><div className="w-10 h-10 rounded-xl bg-[#C9973C]/25 border border-[#C9973C]/40 flex items-center justify-center text-[#FEB922] shrink-0">{React.cloneElement(icon,{className:'w-5 h-5'})}</div><div><h4 className="text-white font-bold text-sm">{title}</h4><p className="text-stone-300 text-xs">{text}</p></div></div>;
