import React, { useState } from 'react';
import { WHATSAPP_NUMBER } from '../data/siteData';
import { Send, FileCheck } from 'lucide-react';

export const MultiStepConsultation: React.FC = () => {
  const [serviceType, setServiceType] = useState('تحديث صك ورقي إلى صك إلكتروني');
  const [city, setCity] = useState('الرياض');
  const [ownerType, setOwnerType] = useState('مالك أصيل');
  const handleSubmit = (e: React.FormEvent) => { e.preventDefault(); const message = `*طلب استشارة سريعة لتحديث صك عقاري (مكتب ريان للمساحة والاستشارات الهندسية)*\n\n📌 صفة المستفيد: ${ownerType}\n📋 الخدمة المطلوبة: ${serviceType}\n📍 المدينة: ${city}`; window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`, '_blank', 'noopener,noreferrer'); };
  return <div className="bg-white/95 backdrop-blur-md rounded-2xl p-6 sm:p-8 shadow-2xl border border-stone-200/80"><div className="flex items-center justify-between mb-6 pb-4 border-b border-stone-200"><div><span className="text-xs font-bold text-[#C9973C] bg-amber-50 px-2.5 py-1 rounded-full border border-amber-200">خدمة إلكترونية فورية</span><h3 className="text-xl font-bold text-[#2B0F16] mt-1.5">طلب دراسة صك واستشارة</h3></div><div className="w-10 h-10 rounded-full bg-emerald-50 border border-emerald-200 flex items-center justify-center text-emerald-600"><FileCheck className="w-5 h-5"/></div></div><form onSubmit={handleSubmit} className="space-y-4 text-right"><label className="block text-xs font-bold text-stone-700">الخدمة المطلوبة<select value={serviceType} onChange={e=>setServiceType(e.target.value)} className="mt-1.5 w-full bg-stone-50 border border-stone-300 rounded-xl px-3.5 py-2.5 text-sm font-medium text-stone-800 focus:outline-none focus:border-[#C9973C]"><option value="تحديث صك ورقي إلى صك إلكتروني">تحديث صك ورقي إلى إلكتروني</option><option value="تعديل بيانات صك أو كروكي">تعديل بيانات صك أو كروكي</option><option value="دمج أو فرز صكوك عقارية">دمج أو فرز صكوك عقارية</option><option value="رفع مساحي وإصدار قرار مساحي">رفع مساحي وإصدار قرار مساحي</option><option value="معاملة منصة إحكام">معاملة منصة إحكام</option></select></label><div className="grid grid-cols-2 gap-3"><label className="block text-xs font-bold text-stone-700">المدينة<select value={city} onChange={e=>setCity(e.target.value)} className="mt-1.5 w-full bg-stone-50 border border-stone-300 rounded-xl px-3.5 py-2.5 text-sm font-medium text-stone-800 focus:outline-none focus:border-[#C9973C]"><option>الرياض</option><option>القصيم</option><option>الدمام والشرقية</option><option>جدة ومكة</option><option>منطقة أخرى</option></select></label><label className="block text-xs font-bold text-stone-700">صفة مقدم الطلب<select value={ownerType} onChange={e=>setOwnerType(e.target.value)} className="mt-1.5 w-full bg-stone-50 border border-stone-300 rounded-xl px-3.5 py-2.5 text-sm font-medium text-stone-800 focus:outline-none focus:border-[#C9973C]"><option>مالك أصيل</option><option>وكيل شرعي</option><option>ورثة</option><option>مطور عقاري أو وسيط</option></select></label></div><button type="submit" className="w-full mt-3 bg-[#25D366] hover:bg-[#20bd5a] text-white font-bold py-3 px-6 rounded-xl flex items-center justify-center gap-2 shadow-lg hover:shadow-xl transition-all text-base"><Send className="w-5 h-5"/><span>إرسال المعاملة للمهندس المختص</span></button><p className="text-[11px] text-center text-stone-500 mt-2">⚡ يتم الرد خلال دقائق وتوجيهك للإجراءات والمستندات المطلوبة مجاناً.</p></form></div>;
};
